### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by totallyhuman**
"deault" to "dealt"

I think this is right but (due to my lack of understanding of this) it might also be "default".
EDIT: On second thought... an issue might've been more suitable for this.

### CODE REVIEW

**Comment by CylonicRaider** [comment]
...It's indeed the exact opposite; a database `path` “dealt in memory” would be of... little use for “persistence”. :wink:

**Comment by CylonicRaider** [comment]
To be honest, the colon-less style of specifying defaults may have been suboptimal even from my point of view... :man_shrugging:
I shall push a fix-up.

**Comment by CylonicRaider** [comment]
...I apparently accidentally spooled back your branch (curse you, Git's same-branch-name policy, I **know** what I'm doing), and beg your pardon. Pulling the upstream one should fix that.

**Comment by totallyhuman** [comment]
No problem. XD

**Pull request closed without merging**
